# Generated by Django 6.0.5 on 2026-05-11 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('pediatrician', 'Pediatrician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist')], max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
